config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  get "account", to: "pages#account"

  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :places, only: [:index, :show, :new, :create] do
    resources :visits, only: [:create]
    resources :wishlist_items, only: [:create]
    resources :questions, only: [:new, :create]
  end
  resources :visits, only: [:index] do
    resources :reviews, only: [:new, :create] 
  end
  resources :wishlist_items, only: [:index, :destroy]
  resources :questions, only: [:index ] do
    resources :answers, only: [:new, :create]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar_bottom.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-amandla fixed-bottom mt-67">

  <div class="container px-3">

    <div class="nav-item">
     <%=  link_to places_path do %>
      <i class="fas fa-search"></i>
      <% end %>
    </div>

    <% if controller_name == "wishlist_items" %>

    <div class="nav-item">
     <%=  link_to wishlist_items_path do %>
      <i class="fas fa-heart"></i>
      <% end %>
    <% else %>
    <div class="nav-item">
     <%=  link_to wishlist_items_path do %>
      <i class="far fa-heart"></i>
      <% end %>
    <% end %>

    </div>

    <% if controller_name == "pages" && action_name == "account" %>
      <div class="nav-item">
       <%=  link_to account_path do %>
        <i class="fas fa-user"></i>
        <% end %>
      </div>
    <% else %>
      <div class="nav-item">
       <%=  link_to account_path do %>
        <i class="far fa-user"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/shared/_navbar_main.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-amandla">
  <div class="container px-3">
    <%=  link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dpnjiruwh/image/upload/v1607523164/Amandla_logo_yellow-01_xtdkfg.png" %>
      <% end %>
  </div>
</div>

app/views/shared/_navbar_mixed.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-amandla">
  <div class="container px-3">
    <div class="nav-back">
      <%=  link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dpnjiruwh/image/upload/v1607523164/Amandla_logo_yellow-01_xtdkfg.png" %>
      <% end %>
    </div>
    <div class="nav-title"><%= title %></div>
  </div>
</div>

app/views/shared/_navbar_pages.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-amandla">
  <div class="container px-3">

    <div class="nav-back">
      <% if controller_name == "visits" && action_name == "index" %>
        <%=  link_to account_path do %>
        <i class="fas fa-times"></i>
        <% end %>
      <% elsif controller_name == "questions" && action_name == "index" %>
        <%=  link_to account_path do %>
        <i class="fas fa-times"></i>
        <% end %>
      <% else %>
        <%=  link_to :back do %>
        <i class="fas fa-times"></i>
        <% end %>
      <% end %>
    </div>
    <div class="nav-title"><%= title %></div>
    <div class="nav-empty"></div>
  </div>
</div>

<!-- a conditional if title is set then don't do the regular navbar but the special title and if logo is true also show the amandla logo -->