config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  get "account", to: "pages#account"

  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :places, only: [:index, :show, :new, :create] do
    resources :visits, only: [:create]
    resources :wishlist_items, only: [:create]
    resources :questions, only: [:new, :create]
  end
  resources :visits, only: [:index] do
    resources :reviews, only: [:new, :create] 
  end
  resources :wishlist_items, only: [:index, :destroy]
  resources :questions, only: [:index ] do
    resources :answers, only: [:new, :create]
  end
end

app/views/pages/account.html.erb
<%= render 'shared/navbar_main' %>
  <div class="container mb-67">

    <% if user_signed_in? %>
      <div class="user-info">
        <div class="user-image" >
          <% if @user.photo.attached? %>
            <div class="avatar avatar-bordered py-10" style="background-image: url(<%= cl_image_path @user.photo.key %>);"></div>
          <% else %>
            <div class="avatar avatar-bordered py-10" style="background-image: url(https://image.shutterstock.com/image-vector/default-avatar-profile-icon-grey-260nw-1545687092.jpg);"></div>
          <% end %>
          <%# <div class="avatar avatar-bordered py-10" style="background-image: url(https://avatars0.githubusercontent.com/u/64172452?v=4);"></div> %>
        </div>

        <div class="account-items">
          <% if current_user.place.present? %>
          <div class="account-item">
            <%= link_to questions_path do%>

              <div class= "account-link">
                <i class="fas fa-question account-icon"></i>
                Open Questions
              </div>
            <% end %>
          </div>
          <% end %>

          <div class="account-item">
            <%= link_to visits_path do %>
              <div class= "account-link">
                <i class="fas fa-walking account-icon"></i>
                Recently visited
              </div>
            <%  end  %>
          </div>

          <div class="account-item">
            <%= link_to new_place_path do %>
              <div class= "account-link">
                <i class="fas fa-building account-icon"></i>
                Add your business
              </div>
            <%  end  %>
          </div>
          <hr>
          <div class="account-item">
            <%= link_to edit_user_registration_path do %>
              <div class= "account-link">
                <i class="far fa-edit account-icon"></i>
                Edit profile
              </div>
            <%  end  %>
          </div>
          <div class="account-item">
            <%= link_to destroy_user_session_path, method: :delete do %>
              <div class= "account-link ">
                <i class="fas fa-sign-out-alt account-icon"></i>
                Log out
              </div>
            <%  end  %>

          </div>
        </div>
      </div>
    <% else %>
        <% controller.redirect_to new_user_session_path %>
    <% end %>
  </div>
<%= render 'shared/navbar_bottom' %>

app/views/pages/home.html.erb
<div class="home-wrapper">
    <% if current_user %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
    <% else  %>
      <%= link_to "Login", new_user_session_path, class: "nav-link" %>
    <% end %>
    <div class="home-content">
      <div class="logo-home">
        <img src="https://res.cloudinary.com/dpnjiruwh/image/upload/v1607942783/Amandla_logo_oqhbdp.png" alt="Amandla" width="300px">
      </div>
      <div class="home-text-icon">
        <h2 class="h2-home">Help create the<br>change</h2>
        <i class="fas fa-globe-americas"></i>
        <h5 class="h5-home">SUPPORT BUSINESSES THAT ARE ALIGNED WITH YOUR BELIEFS.</h5>

        <div class="container">
          <div class="row justify-content-center">
            <div class="col-12 col-lg-6">
              <div class="search-section">
                <%= link_to "SEARCH AROUND YOU", "#", id: "my_location", class: "btn-location-home" %>
                <div class="search-bar">
                  <%= form_tag places_path, method: :get do %>
                    <input type="text" id="place_location" name="place[location]" class="form-control" placeholder="...or search by location"  >
                    <%= button_tag(type: "submit", class: "btn-search-home") do %>
                      <i class="fas fa-map-marker-alt"></i>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>