config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  get "account", to: "pages#account"

  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :places, only: [:index, :show, :new, :create] do
    resources :visits, only: [:create]
    resources :wishlist_items, only: [:create]
    resources :questions, only: [:new, :create]
  end
  resources :visits, only: [:index] do
    resources :reviews, only: [:new, :create] 
  end
  resources :wishlist_items, only: [:index, :destroy]
  resources :questions, only: [:index ] do
    resources :answers, only: [:new, :create]
  end
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  acts_as_taggable_on :tags # or whatever you would like to call your tag list.

  has_one_attached :photo
  has_many_attached :photos_venue
  has_many :visits, dependent: :destroy
  has_many :reviews, through: :visits
  has_many :wishlist_items
  has_many :questions, dependent: :destroy
  has_many :answers, through: :questions, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :story, presence: true, length: { minimum: 75 }
  # validates :google_maps_url, presence: true

  # list of tags with method

  def self.all_tags
    [
    "plant-based",
    "LGBT-friendly",
    "women owned",
    "locally sourced",
    "fair trade",
    "organic",
    "vegetarian"
    ]
  end
  # list of categories with method
  def self.all_cats
    [
    "Restaurant",
    "Bar",
    "Cafe",
    "Groceries",
    "Clothing and Fabrics",
    "Beauty and Wellness"
    ]
  end

  def average_reviews
    #total_reviews = 0
    total_reviews = self.reviews.count
    return 0 if total_reviews == 0
    self.reviews.sum(:rating).to_f / total_reviews
  end

  def distance_to_place(current_lat, current_lon, place_lat, place_lon)
    Geocoder::Calculations.distance_between([current_lat, current_lon], [place_lat, place_lon])
    # Geocoder::Calculations.distance_between([47.858205, 2.294359], [40.748433, -73.985655])
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]
  def index

    location_coord

    filter_by_location



    @markers = @places.map do |place|

      {
        lat: place.latitude,
        lng: place.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { place: place }),
        image_url: helpers.asset_url('https://res.cloudinary.com/dpnjiruwh/image/upload/v1608203373/amandla_map_placeholder_1_n9cmqd.png')
      }
    end
  end

  def show
    @place = Place.find(params[:id])
    # @questions = Question.find(@place.question_ids)
    @answered_questions = @place.user.answered_questions.reverse
    @markers = [{
      lat: @place.latitude,
      lng: @place.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { place: @place }),
      image_url: helpers.asset_url('https://res.cloudinary.com/dpnjiruwh/image/upload/v1608203373/amandla_map_placeholder_1_n9cmqd.png')
    }]
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    @place.user = current_user
    if @place.save
      redirect_to place_path(@place)
    else
      render :new # jumps to view "new"
    end
  end

  private

  def place_params
    params.require(:place).permit(:name, :address, :category, :story, :photo, tag_list: [], photos_venue: [])
  end

  def filter_by_location
    if params[:place] && params[:place][:location].present?
      @places = Place.geocoded.near(params[:place][:location], 10)
    else
      @places = Place.geocoded
    end
    if params[:place] && params[:place][:category].present?
      @places = @places.select { |place| place.category == params[:place][:category] }
    end
    if params[:place] && params[:place][:tag_list] && params[:place][:tag_list][1].present?
      @places = @places.select { |place| params[:place][:tag_list].drop(1).all? { |tag| place.tag_list.include?(tag) } }
    end
  end

  def location_coord
    if params[:place] && params[:place][:location].present?
      @location_coord = Geocoder.search(params[:place][:location]).first.coordinates
    else
      @location_coord = [41.40539057735755, 2.1647695790020993] # lewagon barcelona
    end
  end

end

app/views/places/_filter_places.html.erb
<div class="d-none" id="search-filter">
  <a href="/places" class="icons clear">
    <i class="fas fa-smile"></i> Give me all!
  </a>
  <%= simple_form_for :place, url: places_path, method: :get  do |f| %>
    <div class="form container">
      <%= f.input :location, :label => "Find by location", required: false %>
      <%= f.input :category, as: :radio_buttons,
          collection_wrapper_tag: 'div',
          collection_wrapper_class: 'category-wrapper',
          item_wrapper_class: 'category-item',
          input_html: {class: 'category-selector'},
          :label => "Type of business (Choose only one)",
          as: :radio_buttons, collection: Place.all_cats %>

      <%= f.input :tag_list, as: :radio_buttons,
          collection_wrapper_tag: 'div',
          collection_wrapper_class: 'category-wrapper',
          item_wrapper_class: 'category-item',
          input_html: {class: 'category-selector'},
          :label => "Which critiria do you fulfil? (Choose as many you need)",
          as: :check_boxes, collection: Place.all_tags %>
    </div>
    <%= f.submit "Apply filters",  class:"btn-apply-filters px-0" %>
  <% end %>
</div>

app/views/places/_info_window.html.erb
<div class="card-container-map">
  <%= link_to place_path(place), class: "place-card-link" do %>
  <% if place.photo.attached? %>
  <div class="card-image-map" style="background-image: linear-gradient(180deg, rgba(52, 100, 109, 0.08) 0%, rgba(15, 29, 31, 0.6) 100%), url(<%= cl_image_path place.photo.key, crop: :fit%>)">
  <% else %>
  <div class="card-image-map" style="background-image: linear-gradient(180deg, rgba(52, 100, 109, 0.08) 0%, rgba(15, 29, 31, 0.6) 100%), url(<%= cl_image_path "p1xxchyw9ygjdeiqaa1sp47g2zgw", crop: :fit%>)">
  <% end %>

    <div class="card-place-name-map"><%= place.name.capitalize %></div>
    <br>
    <div class="card-category-map"><%= place.category %></div>

  </div>
  <% end %>
</div>

app/views/places/index.html.erb
<%= render 'shared/navbar_main' %>
<%= render 'filter_places' %>
<div class="index-container ">

  <div class="top-container">
    <div class="container pl-0">
    Your search results
      <div class="icons" >
          <div id="search-filter-btn">
            <i class="fas fa-sliders-h indexicon"></i>
          </div>
      <div class="right-icon ml-3">
        <div class="search-map-btn">
          <i class="fas fa-map-marked-alt indexicon"></i>
        </div>
        <div class="search-list-btn d-none">
          <i class="fas fa-list-ul indexicon"></i>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <!-- This div is centered and takes 6 columns -->


        <div class="card-container mt-3 pt-3">
            <% @places.each do |place| %>

                <div class="place-card" id="place_<%= place.id %>">
                  <% if user_signed_in? %>
                    <% if current_user.on_wishlist?(place) %>
                          <%=  link_to wishlist_item_path(current_user.wishlist_item_of(place)), method: :delete, remote: true do %>
                            <i class="fas fa-heart wish-icon"></i>
                          <% end  %>
                      <% else %>
                        <%=  link_to place_wishlist_items_path(place), method: :post, remote: true do %>
                          <i class="far fa-heart wish-icon"></i>
                        <% end  %>
                      <% end %>
                    <% end %>
                  <%= link_to place_path(place), class: "place-card-link" do %>
                  <% if place.photo.attached? %>
                  <div class="card-image" style="background-image: linear-gradient(180deg, rgba(52, 100, 109, 0.08) 0%, rgba(15, 29, 31, 0.6) 100%), url(<%= cl_image_path place.photo.key, crop: :fit%>)">
                  <% else %>
                  <div class="card-image" style="background-image: linear-gradient(180deg, rgba(52, 100, 109, 0.08) 0%, rgba(15, 29, 31, 0.6) 100%), url(<%= cl_image_path "p1xxchyw9ygjdeiqaa1sp47g2zgw", crop: :fit%>)">
                  <% end %>

                    <div class="card-place-name"><%= place.name.capitalize %></div>
                    <% place.tag_list.each do |tag| %>
                      <div class="card-tags"><%= tag %></div>
                    <% end %>
                  </div>
                  <div class="card-details">
                    <div class="item"><i class="fas fa-seedling"></i>
                      <%= (place.average_reviews).truncate(1) %>
                    </div>
                    <% if params[:place] && params[:place][:location].present? %>
                      <div class="item">
                        <%= (place.distance_to_place(@location_coord[0], @location_coord[1], place.latitude, place.longitude)).truncate(1) %> km
                      </div>
                    <% end %>
                  </div>
                <% end %>
              </div>
            <% end %>
        </div>




      </div>
    </div>
  </div>


</div>


  <div id="map" class="d-none"
     style="width: 100%; height: 800px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">

  </div>
   <div style="margin-bottom: 67px">
  </div>





<%= render 'shared/navbar_bottom' %>

app/views/places/new.html.erb
<%= render 'shared/navbar_pages', title: 'Add your business' %>

    <%= simple_form_for [@place] do |f| %>
      <div class="form container">
        <div class="form-inputs">
        <%= f.input :name, :label => "What's your business name?" %>
        <%= f.input :address, :label => "What's the address?" %>
        <%= f.input :category, as: :radio_buttons,
            collection_wrapper_tag: 'div',
            collection_wrapper_class: 'category-wrapper',
            item_wrapper_class: 'category-item',
            input_html: {class: 'category-selector'},
            :label => "Type of business (Choose only one)",
            as: :radio_buttons, collection: Place.all_cats %>

        <%= f.input :tag_list, as: :radio_buttons,
            collection_wrapper_tag: 'div',
            collection_wrapper_class: 'category-wrapper',
            item_wrapper_class: 'category-item',
            input_html: {class: 'category-selector'},
            :label => "Which criteria do you fulfil? (Choose as many you think)",
            as: :check_boxes, collection: Place.all_tags %>

        <%= f.input :story, :label => "Tell us more (will be displayed)", :input_html => {:rows => 10} %>

        <div class="justify-content-between pb-3">
          <%= f.input :photo, input_html: { class: 'd-none', id: 'photo-input'},
            wrapper_html: { class: 'mb-0 d-flex align-items-center'},
            label_html: { class: 'upload-photo mb-0'},
            label: '📷 Primary photo',
            as: :file %>
          <%= image_tag "", width: 200, class: "d-none mt-3 ", id: "photo-preview" %>
        </div>
        <div class="container p-0">
        <%= f.input :photos_venue, as: :file, input_html: { multiple: true, class: 'd-none' },
            wrapper_html: { class: 'mb-0 d-flex align-items-center'},
            label_html: { class: 'upload-photo mb-0'},
            label: '📷 Aditional photos',
            as: :file %>
            <div class="my-3" id="results">

            </div>
            <%="Note: After clicking 'create', your business will go through a verification process. We will be in touch with regards to that soon."%>
        </div>
      </div>
      </div>
      <%= f.submit "Create",  class:"btn-create-business px-0" %>
    <% end %>

app/views/places/show.html.erb
<%= render 'shared/navbar_main' %>


<div class="banner-show" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.2)), url(<%= cl_image_path @place.photo.key, crop: :fill %>)">
  <%=  link_to places_path do %>
    <i class="fas fa-times back-icon-show"></i>
  <% end %>

  <% if current_user.on_wishlist?(@place) %>
    <%=  link_to wishlist_item_path(current_user.wishlist_item_of(@place), show: true), method: :delete, remote: true do %>
      <i class="fas fa-heart wish-icon-show"></i>
    <% end  %>
  <% else %>
    <%=  link_to place_wishlist_items_path(@place, show: true), method: :post, remote: true do %>
      <i class="far fa-heart wish-icon-show"></i>
    <% end  %>
  <% end %>
  <h1><%= @place.name %> </h1>
  <h6><%= @place.category %> </h6>
  <h6 class="rating-place">
    <i class="fas fa-seedling"></i>
    <% if @place.reviews.empty? %>
      -
    <% else %>
      <%= (@place.average_reviews).truncate(1) %>
    <% end %>
  </h6>
  <% if @place.user.photo.attached? %>
    <div class="avatar-show avatar-bordered" style="background-image: url(<%= cl_image_path @place.user.photo.key %>);">
  <% else %>
    <div class="avatar-show avatar-bordered" style="background-image: url(https://image.shutterstock.com/image-vector/default-avatar-profile-icon-grey-260nw-1545687092.jpg);">
  <% end %>
  </div>
</div>







<div class="card-show">
  <p><strong><%= @place.user.first_name %></strong>  </p>

  <div class="d-flex justify-content-center">
    <% @place.tag_list.each do |tag|%>
      <% if tag == "plant-based" %>
        <div class="text-center mx-1">
          <i class="fas fa-leaf tag-icons"></i>
          <p id="text-green"><%= tag  %></p>
        </div>
      <% end %>
      <% if tag == "LGBT-friendly" %>
        <div class="text-center mx-1">
          <i class="fas fa-rainbow tag-icons"></i>
          <p id="text-green"><%= tag  %></p>
        </div>
      <% end %>
      <% if tag == "women owned" %>
        <div class="text-center mx-1">
          <i class="fas fa-venus-double tag-icons"></i>
          <p id="text-green"><%= tag  %></p>
        </div>
      <% end %>
      <% if tag == "locally sourced" %>
        <div class="text-center mx-1">
          <i class="fas fa-street-view tag-icons"></i>
          <p id="text-green"><%= tag  %></p>
        </div>
      <% end %>
      <% if tag == "fair trade" %>
        <div class="text-center mx-1">
          <i class="far fa-handshake tag-icons"></i>
          <p id="text-green"><%= tag  %></p>
        </div>
      <% end %>
      <% if tag == "organic" %>
        <div class="text-center mx-1">
          <i class="fab fa-envira tag-icons"></i>
          <p id="text-green"><%= tag  %></p>
        </div>
      <% end %>
      <% if tag == "vegetarian" %>
        <div class="text-center mx-1">
          <i class="fas fa-pepper-hot tag-icons"></i>
          <p id="text-green"><%= tag  %></p>
        </div>
      <% end %>
    <% end %>
  </div>



  <p class="p-4"><strong><%= (@place.user.about_me).upcase %></strong> </p>



  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <!-- This div is centered and takes 6 columns -->

        <% if @place.photos_venue.attached? %>

          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">

            <% @place.photos_venue.each do |photo| %>
              <div class="carousel-item <%= "active" if @place.photos_venue.first == photo %>">
                <img src="<%= cl_image_path photo.key %>" class="d-block w-100" alt="...">
              </div>
          <% end %>

            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>

        <% else %>
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="https://images.adsttc.com/media/images/5de8/74f9/3312/fdbc/3500/005b/newsletter/Culturist_5.jpg?1575515353" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="https://res.cloudinary.com/dpnjiruwh/image/upload/v1607529121/images_xf4hsk.jpg" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="https://soycomocomo.es/media/2018/06/forn-veritas.jpg" class="d-block w-100" alt="...">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        <% end %>



      </div>
    </div>
  </div>







<div>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-8">

        <div class="story-show py-4 mx-0">
          <h5 id="about-place">About <%= @place.name %> </h5>
          <p><%= @place.story %> </p>
        </div>


      </div>
    </div>
  </div>



    <div class="question-answer p-4 pb-5">

      <div class="container">
        <div class="row justify-content-center">
          <div class="col-12 col-lg-8">
            <!-- This div is centered and takes 6 columns -->

            <h5>Ask <%= @place.user.first_name %> anything: </h5>

              <% @answered_questions.first(3).each do |question| %>
                <h6> <strong>Q:</strong>  <%= question.content %> </h6>
                <p> <%= question.user.first_name %>, <%= question.created_at.strftime("%b %d, %Y") %></p>
                <h6> A: <%= question.answer.content %> </h6>
                <hr>
              <% end %>



          </div>


        </div>
        <div class="container mt-5">
          <div class="row justify-content-center">
            <div class="col-12 col-lg-8">
              <!-- This div is centered and takes 6 columns -->

              <% if @answered_questions.count > 3 %>
                <p>
                  <a class="btn-link-green position-bottom-left" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                    SHOW MORE <i class="fas fa-caret-down"></i>
                  </a>
                </p>

                <div class="collapse" id="collapseExample">
                  <div class="ratings-people">
                    <% @answered_questions[3..-1].each do |question| %>
                      <h6> <strong>Q:</strong>  <%= question.content %> </h6>
                      <p> <%= question.user.first_name %>, <%= question.created_at.strftime("%b %d, %Y") %></p>
                      <h6> A: <%= question.answer.content %> </h6>
                      <hr>
                    <% end %>
                  </div>
                </div>
              <% end %>
              <%= link_to "ASK THE OWNER", new_place_question_path(@place), class: 'btn-dark-green position-bottom' %>

            </div>
          </div>
        </div>
      </div>

    </div>

    <div class="ratings-show p-4 pb-5">

      <div class="container">
        <div class="row justify-content-center">
          <div class="col-12 col-lg-8">
            <!-- This div is centered and takes 6 columns -->

            <div class="d-flex justify-content-between">
              <div class="d-flex justify-content-start mt-3 ml-0 ratings-global">
                <i class="fas fa-seedling" id="leaf"></i>
                <p id="rating-number">
                  <% if @place.reviews.empty? %>
                    -
                  <% else %>
                    <%= (@place.average_reviews).truncate(1) %>
                  <% end %>
                </p>
              </div>
              <div class="d-flex justify-content-end">
                <p class="opinions"> <%= @place.reviews.count %> reviews</p>
              </div>
            </div>


            <% if @place.reviews.count > 0 %>
              <% @place.reviews.first(3).each do |review| %>
                <p id="who-said"> <%= review.visit.user.first_name %>, <%= review.created_at.strftime("%b %d, %Y") %> </p>

                <h6 class="ratings-people"><%= review.content  %></h6>
                <div class="d-flex justify-content-left mt-3 ml-0 little-rating">
                  <p id="really-little"><%= review.rating %>
                    <% if review.rating == 5 %>
                      </p><i class="fas fa-seedling leafy"></i><i class="fas fa-seedling leafy"></i> <i class="fas fa-seedling leafy"></i> <i class="fas fa-seedling leafy"></i> <i class="fas fa-seedling leafy"></i>
                    <% end %>
                    <% if review.rating == 4 %>
                      </p><i class="fas fa-seedling leafy"></i><i class="fas fa-seedling leafy"></i> <i class="fas fa-seedling leafy"></i> <i class="fas fa-seedling leafy"></i>
                    <% end %>
                    <% if review.rating == 3 %>
                      </p><i class="fas fa-seedling leafy"></i><i class="fas fa-seedling leafy"></i> <i class="fas fa-seedling leafy"></i>
                    <% end %>
                    <% if review.rating == 2 %>
                      </p><i class="fas fa-seedling leafy"></i><i class="fas fa-seedling leafy"></i>
                    <% end %>
                    <% if review.rating == 1 %>
                      </p><i class="fas fa-seedling leafy"></i>
                    <% end %>
                </div>
                <hr>
              <% end %>

              <% if @place.reviews.count > 3 %>
                <p>
                  <a class="btn-link-green position-bottom-left" data-toggle="collapse" href="#collapseReviews" role="button" aria-expanded="false" aria-controls="collapseReviews">
                    SHOW MORE <i class="fas fa-caret-down"></i>
                  </a>
                </p>
                <div class="collapse" id="collapseReviews">
                  <div class="ratings-people">

                      <% @place.reviews[3..-1].each do |review| %>
                        <p id="who-said"> <%= review.visit.user.first_name %>, <%= review.created_at.strftime("%b %d, %Y") %> </p>

                        <h6 class="ratings-people"><%= review.content  %></h6>
                        <div class="d-flex justify-content-left mt-3 ml-0 little-rating">
                          <p id="really-little"><%= review.rating %>
                            <% if review.rating == 5 %>
                              </p><i class="fas fa-seedling leafy"></i><i class="fas fa-seedling leafy"></i> <i class="fas fa-seedling leafy"></i> <i class="fas fa-seedling leafy"></i> <i class="fas fa-seedling leafy"></i>
                            <% end %>
                            <% if review.rating == 4 %>
                              </p><i class="fas fa-seedling leafy"></i><i class="fas fa-seedling leafy"></i> <i class="fas fa-seedling leafy"></i> <i class="fas fa-seedling leafy"></i>
                            <% end %>
                            <% if review.rating == 3 %>
                              </p><i class="fas fa-seedling leafy"></i><i class="fas fa-seedling leafy"></i> <i class="fas fa-seedling leafy"></i>
                            <% end %>
                            <% if review.rating == 2 %>
                              </p><i class="fas fa-seedling leafy"></i><i class="fas fa-seedling leafy"></i>
                            <% end %>
                            <% if review.rating == 1 %>
                              </p><i class="fas fa-seedling leafy"></i>
                            <% end %>
                        </div>
                        <hr>
                      <% end %>
              <% end %>

            <% else %>
                  <p>No reviews yet!</p>
            <% end %>
              </div>
            </div>


          </div>
        </div>
      </div>


      <% if current_user.visits.any? { |visit| visit.place == @place } %>
        <%= button_to "LEAVE AN OPINION", new_visit_review_path(current_user.visits.find_by(place: @place)), class: "btn-dark-green position-bottom", method: :get %>
      <% end %>
    </div>



</div>
  <div id="map" class="map-in-show"
     style="width: 100%; height: 600px; margin-bottom: 11px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>


  </div>

    </div>
<%= render 'shared/navbar_bottom' %>




<% #add googlr maps link to place,place_visits_path(@place) %>
<%= link_to "Lets go!", place_visits_path(@place), method: :post, class: 'card-link' %>